name: 'Docker Run Action'
description: 'Run a command in a new container'
inputs:
  image:
    description: "The Docker image to run"
    required: true
  options:
    description: 'Options'
    required: false
  run:
    description: 'Run command in container'
    required: true
  services:
    description: 'List of services to start'
    required: false
    default: 'web'
  compose_file:
    description: 'The docker-compose file to use'
    required: false
    default: 'docker-compose.ci.yml'
runs:
  using: 'composite'
  steps:
    - name: Run Docker Container
      shell: bash
      env:
        DOCKER_VERSION: ${{ inputs.version }}
        COMPOSE_FILE: ${{ inputs.compose_file }}
      run: |
        # Start the specified services
        make docker_compose_up DOCKER_SERVICES="${{ inputs.services }}"

        cat <<'EOF' | docker compose exec web sh
          ${{ inputs.run }}
        EOF
