name: 'Docker Run Action'
description: 'Run a command in a new container'
inputs:
  version:
    description: 'The version of the image to run'
    required: true
  run:
    description: 'Run command in container'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Run Docker Container
      shell: bash
      env:
        DOCKER_VERSION: ${{ inputs.version }}
      run: |
        cat <<'EOF' | docker compose run web sh
          ${{ inputs.run }}
        EOF

    - name: Logs
      shell: bash
      if: failure()
      run: docker compose logs
