name: 'Docker Run Action'
description: 'Run a command in a new container'
inputs:
  version:
    description: 'The version of the image to run. Supports tag name or digest'
    required: true
    default: 'local'
  build:
    description: 'Build the image before running'
    required: false
    default: ''
  run:
    description: 'Run command in container'
    required: true
  services:
    description: 'List of services to start'
    required: false
    default: 'web'
  compose_file:
    description: 'The docker-compose file to use'
    required: false
    default: 'docker-compose.yml'
runs:
  using: 'composite'
  steps:
    - id: id
      shell: bash
      run: |
        echo "id=$(id -u)" >> $GITHUB_OUTPUT

    - name: Run Docker Container
      shell: bash
      env:
        DOCKER_BUILD: ${{ inputs.build }}
        DOCKER_VERSION: ${{ inputs.version }}
        COMPOSE_FILE: ${{ inputs.compose_file }}
        DOCKER_SERVICES: ${{ inputs.services }}
        HOST_UID: ${{ steps.id.outputs.id }}
      run: |
        if [[ -z '${{ inputs.run }}' ]]; then
          echo "run input is required"
          exit 1
        fi

        # Create correct environment variables
        make create_env_file

        # Start the specified services
        make up

        # Exec the run command in the container
        # quoted 'EOF' to prevent variable expansion
        cat <<'EOF' | docker compose exec --user olympia web sh
          ${{ inputs.run }}
        EOF

    - name: Logs
      shell: bash
      if: failure()
      run: docker compose logs
