name: 'Docker Run Action'
description: 'Run a command in docker compose web container'
inputs:
  command:
    description: 'The command to run in The container'
    required: true
  version:
    description: 'The version of the image to run'
    required: true
  up:
    description: 'List of services to start'
    required: false
    default: 'web'
  compose_file:
    description: 'The docker-compose file to use'
    required: false
    default: 'docker-compose.ci.yml'
runs:
  using: 'composite'
  steps:
    - name: Export environment
      shell: bash
      run: |
        # Define environment variables needed for the docker-compose file
        make create_env_file DOCKER_VERSION="${{ inputs.version }}"

        echo "COMPOSE_FILE=${{ inputs.compose_file }}" >> .env

    - name: Docker Compose Up
      shell: bash
      run: |
        # Start the services and prevent re-building any images
        make docker_compose_up DOCKER_SERVICES="${{ inputs.up }}"

    - name: Docker Compose Exec
      shell: bash
      run: |
        cat <<EOF | docker compose exec web sh
          /data/olympia/docker/fix_olympia_user.sh "${{ inputs.command }}"
        EOF

    - name: Logs
      shell: bash
      if: failure()
      run: docker compose logs
