name: 'Docker Run Action'
description: 'Run a command in docker compose web container'
inputs:
  command:
    description: 'The command to run in The container'
    required: true
  version:
    description: 'The version of the image to run'
    required: true
  up:
    description: 'List of services to start'
    required: false
    default: 'web'
  env:
    description: 'The environment variables to pass to the container'
    required: false
    default: ''
  copy:
    description: 'Copy /data/olympia to the action workspace'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Export environment
      shell: bash
      run: |
        # Define environment variables needed for the docker-compose file
        make create_env_file DOCKER_VERSION="${{ inputs.version }}" UID=9500 GID=9500

        echo "${{ inputs.env }}" >> .env
        # Only use the base docker-compose file
        # Prevents building or mounting volumes.
        # Here we just want to pull the specified version and run the command
        echo "COMPOSE_FILE=docker-compose.yml:docker-compose.build.yml" >> .env

    - name: Docker Compose Up
      shell: bash
      run: |
        docker compose up ${{ inputs.up }} \
          -d \
          --wait \
          --remove-orphans \
          --force-recreate \
          --quiet-pull


    - name: Docker Compose Exec
      shell: bash
      run: |
        cat <<EOF > exec.sh
          #!/bin/bash
          printenv
          /data/olympia/docker/entrypoint.sh "${{ inputs.command }}"
        EOF

        chmod +x exec.sh

        # Execute the Command on web
        cat exec.sh | docker compose exec web sh

        if [[ "${{ inputs.copy }}" == 'true' ]]; then
          docker compose exec web tar -C /data/olympia -cf - . | tar -xf -
        fi



    - name: Logs
      shell: bash
      if: failure()
      run: docker compose logs
