networks:
  default:

volumes:
  data_redis:
  data_elasticsearch:
  data_mysqld:
    name: ${DOCKER_MYSQLD_VOLUME:-}
    external: true
  data_rabbitmq:
  storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/storage
