services:
  web:
    extends:
      file: docker-compose._base.yml
      service: web
    volumes:
      - ./deps:/_deps
    command:
      - |
        chown -R olympia:olympia /_deps
        cp -r /deps/** /_deps/
