include:
  - path:
      - docker-compose._services.yml

services:
  web:
    extends:
      file: docker-compose._web.yml
      service: web
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
      x-bake:
        pull: true
        platforms: linux/amd64
    volumes:
      - .:/data/olympia
      - ./deps:/deps
      - ./package.json:/deps/package.json
      - ./package-lock.json:/deps/package-lock.json

  worker:
    extends:
      service: web
    command:
      - supervisord -n -c /data/olympia/docker/supervisor-celery.conf
