services:
  worker:
    environment:
    # Note: docker compose uses the values exported from .env for HOST_UID if
    # it exists. ./docker/entrypoint.sh uses this variable to fix
    # the uid of the olympia user to match the host user id if necessary.
    - HOST_UID=${HOST_UID:-}
    volumes:
      - .:/data/olympia
      - /data/olympia/src/olympia.egg-info
  web:
    extends:
      service: worker
