# Using this file enables a mount of ./deps to /deps in the web/worker containers.
# This allows the /deps folder to be exposed on the host machine enabling editing of those files
# from the host. It is disabled by default.
services:
  olympia:
    build:
      x-bake:
        target: olympia
  worker:
    develop:
      watch:
        - action: sync+restart
          path: ./src/olympia
          target: /data/olympia/src/olympia
    volumes:
      - storage:/data/olympia/storage
      - ./deps:/deps

  web:
    extends: worker
