services:
  olympia:
    image: mozilla/addons-server${DOCKER_VERSION:-}
    # We drop down to a different user through supervisord, but starting as
    # root allows us to fix the ownership of files generated at image build
    # time through the ./docker/entrypoint.sh script.
    user: root
    platform: linux/amd64
    entrypoint: ["/data/olympia/docker/entrypoint.sh"]
    volumes:
      - storage:/data/olympia/storage
      - deps:/deps
      - ./package.json:/deps/package.json
      - ./package-lock.json:/deps/package-lock.json

    extra_hosts:
     - "olympia.test:127.0.0.1"
    restart: on-failure:5
