version: "3.8"

services:
  worker: &worker
    build:
        context: .
        dockerfile: Dockerfile
        target: development
        args:
          - OLYMPIA_UID
          - OLYMPIA_GID
          - DEPS
          - MODE

  web:
    <<: *worker
