# These environment variables must be set in CircleCI UI
#
# DOCKERHUB_REPO - docker hub repo, format: <username>/<repo>
# DOCKER_USER - Login user for docker hub
# DOCKER_PASS - Login password for docker hub user
version: 2.1

references:
  defaults-release: &defaults-release
    machine:
      image: ubuntu-2004:current
    working_directory: "~/addons-server"

commands:
  make_release:
    description: "Builds and pushes a Docker image"
    parameters:
      push:
        type: boolean
        default: false
      image_tag:
        type: string
        default: "latest"
    steps:
      - run:
          name: Set environment variables
          command: |
            echo 'export DOCKER_VERSION=<< parameters.image_tag >>' >> $BASH_ENV
            echo 'export DOCKER_COMMIT=$CIRCLE_SHA1' >> $BASH_ENV
            echo 'export VERSION_BUILD_URL=$CIRCLE_BUILD_URL' >> $BASH_ENV
            echo 'export DOCKER_PUSH=<< parameters.push >>' >> $BASH_ENV
      - run:
          name: Build docker image and push to repo
          command: |
            docker version
            docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASS}"
            make build_docker_image

jobs:
  # Add to a workflow, if you want to test the docker build in circleci
  build-image:
    <<: *defaults-release
    steps:
      - checkout
      - make_release:
          image_tag: ${CIRCLE_BRANCH}
          # explicitly don't push
          push: false

  release-master:
    <<: *defaults-release
    steps:
      - checkout
      - make_release:
          image_tag: latest
          push: true

  release-tag:
    <<: *defaults-release
    steps:
      - checkout
      - make_release:
          image_tag: "${CIRCLE_TAG}"
          push: true

workflows:
  version: 2
  default-workflow:
    jobs:
      # Uncomment if you want to test the docker build
      - build-image
      - release-master:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - release-tag:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
