name: 'Restore ./deps cache'
description: 'Tries to restore ./deps from cache, installing fresh if missing'
runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v3
      id: cache
      with:
        path: ${{ github.workspace }}/deps
        key: deps_cache-${{ runner.os }}-${{ github.run_id }}
        restore-keys: |
          pip-${{ hashFiles('requirements/**') }}
          node-${{ hashFiles('package*.json') }}

    - name: Install Dependencies
      shell: bash
      env:
        DOCKER_SERVICES: deps_container
        COMPOSE_FILE: docker-compose.yml:docker-compose.build.yml
        DOCKER_DETATCH: 'false'
      run: |
        # This command will wait until dependencies have been copied to ./deps
        make up
