name: 'Push docker image from artifact'
description: 'Pushes a local docker image to a registry'
inputs:
    to_registry:
      required: true
      description: docker registry to publish to
    to_image:
      required: true
      description: docker image to tag the image
    to_version:
      required: true
      description: docker image version to tag the image
    from_tag:
      required: true
      description: the docker image to tag from
    username:
      required: true
      description: the username to login with
    password:
      required: true
      description: the password to login with

outputs:
  digest:
    description: The image digest from the index.json
    value: ${{ steps.load.outputs.digest }}

runs:
  using: 'composite'
  steps:
    - name: Login
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.to_registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Push the produciton image
      shell: bash
      run: |
        # The tag for the image from the downloaded artifact
        from_tag="${{ inputs.from_tag }}"

        # The tag for the image to be published in the registry
        registry="${{ inputs.to_registry }}"
        image="${{ inputs.to_image }}"
        version="${{ inputs.to_version }}"
        # TODO: before enabling this in production we should remove -next
        publish_tag="$registry/$image:$version-next"

        echo "Tagging $from_tag -> $publish_tag"
        docker tag $from_tag $publish_tag

        echo "Pushing $publish_tag to $registry"
        docker push $publish_tag

