name: Test Docker Image

run-name: |
  ref: ${{ github.ref_name }} |
  version: ${{ inputs.version }} |
  digest: ${{ inputs.digest }} |

on:
  workflow_call:
    inputs:
      version:
        description: The version of the image to run
        type: string
        required: false
      digest:
        description: The build digest of the image to run. Overrides version.
        type: string
        required: false
  workflow_dispatch:
    inputs:
      version:
        description: The version of the image to run
        type: string
        required: false
      digest:
        description: The build digest of the image to run. Overrides version.
        type: string
        required: false

concurrency:
  group: test-${{ github.workflow }}-${{ github.event_name}}-${{ github.ref}}-${{ toJson(inputs) }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          -
            name: Needs Locale Compilation
            run: make test_needs_locales_compilation
          -
            name: Static Assets
            run: make test_static_assets
          -
            name: Internal Routes
            run: make test_internal_routes_allowed
          -
            name: Elastic Search
            run: make test_es_tests
          -
            name: Manage Check
            run: make check
    steps:
      - uses: actions/checkout@v4
      - name: Test (${{ matrix.name }})
        uses: ./.github/actions/run-docker
        with:
          version: ${{ inputs.version }}
          digest: ${{ inputs.digest }}
          run: ${{ matrix.run }}
