name: Build Docker Images

on:
  workflow_call:
    inputs:
      image:
        description: The docker image to tag with
        type: string
        required: false
        default: ${{ github.repository }}
      target:
        description: The target of the image to build
        type: string
        required: true
    outputs:
      artifact_name:
        description: The name of the artifact where the development image was uploaded
        value: ${{ jobs.build.outputs.artifact_name }}
      version:
        description: The docker version of the built images
        value: ${{ jobs.build.outputs.version }}

concurrency:
  # TODO fix concurrency
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

env:
  build_docker_artifact: build-docker
  # This value must be kept in sync with `run-docker`
  # So we know where to load the docker image from
  build_docker_image_file: image.tar

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.docker_meta.outputs.version }}

      tags: ${{ steps.docker_meta.outputs.tags }}
      annotations: ${{ steps.docker_meta.outputs.annotations }}
      labels: ${{ steps.docker_meta.outputs.labels }}

      artifact_name: ${{ steps.artifact_meta.outputs.artifact_name }}

    steps:
      - uses: actions/checkout@v4

      - id: artifact_meta
        shell: bash
        run: |
          echo "artifact_name=build-docker-${{ inputs.target }}" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image }}
          flavor: |
            suffix=-next
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=ref,event=pr

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          buildkitd-flags: --debug

      - name: Local Environment Setup
        shell: bash
        env:
          DOCKER_VERSION: ${{ steps.docker_meta.outputs.version }}
          DOCKER_COMMIT: ${{ github.sha }}
          VERSION_BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          # Create the .env file
          make setup

      - name: Build Docker Image
        id: build
        uses: docker/build-push-action@v6
        with:
          # Build Context
          context: .
          file: Dockerfile
          target: ${{ inputs.target }}
          platforms: linux/amd64

          # Export the image to `image.tar`
          push: false
          load: false
          outputs: |
            type=docker,dest=${{ env.build_docker_image_file }}

          # Metadata
          tags: ${{ steps.docker_meta.outputs.tags }}
          annotations: ${{ steps.docker_meta.outputs.annotations }}
          labels: ${{ steps.docker_meta.outputs.labels }}

          # Cache Information
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload Development Image
        uses: actions/upload-artifact@v4
        with:
          # We need to upload to a named artifact that is exposed to `run-docker`
          name: ${{ steps.artifact_meta.outputs.artifact_name }}
          # Upload just the single tar file
          path: ${{ env.build_docker_image_file }}
          # We expect artifacts to be found, explicitly error if none are
          if-no-files-found: error
          # Artifacts should not last long, each run will create a new one
          retention-days: 1
          # Optimize for speed rather than size
          compression-level: 1
          # We should never create the exact same artifact twice in the same run
          overwrite: false
