name: CI

on: pull_request

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      target: development

  test:
    needs: build
    uses: ./.github/workflows/_test.yml
    with:
      artifact_name: ${{ needs.build.outputs.artifact_name }}

  test_main:
    needs: build
    uses: ./.github/workflows/_test_main.yml
    with:
      artifact_name: ${{ needs.build.outputs.artifact_name }}
