name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.build.outputs.artifact_name }}

    steps:
      - uses: actions/checkout@v4
      - id: build
        uses: ./.github/actions/build-docker
        with:
          registry: docker.io
          image: ${{ github.repository }}
          version: pr-${{ github.event.pull_request.number }}
          target: development

  test:
    needs: build
    uses: ./.github/workflows/_test.yml
    with:
      artifact_name: ${{ needs.build.outputs.artifact_name }}

  test_main:
    needs: build
    uses: ./.github/workflows/_test_main.yml
    with:
      artifact_name: ${{ needs.build.outputs.artifact_name }}
