name: Extract Locales

on:
  push:
    branches:
      - master

jobs:
  extract_locales:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Build Docker image
        id: build
        uses: ./.github/actions/build-docker
        with:
          load: true

      - name: Extract Locales
        uses: ./.github/actions/run-docker
        with:
          version: ${{ steps.build.outputs.version }}
          compose_file: docker-compose.olympia.yml
          command: |
            make extract_locales

      - name: Push Locales
        shell: bash
        run: |
          make push_locales
