name: Push

on:
  push:
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: true

env:
  DOCS_ARTIFACT_NAME: docs

jobs:
  deploy_docs:
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4

      - name: Build Docker image
        id: build
        uses: ./.github/actions/build-docker

      - name: Cache Dependencies Directory
        uses: ./.github/actions/cache-deps

      - name: Build Docs
        uses: ./.github/actions/run-docker
        with:
          version: ${{ steps.build.outputs.version }}
          compose_file: docker-compose.yml
          run: |
            make docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/_build/html'
          name: ${{ env.DOCS_ARTIFACT_NAME}}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ env.DOCS_ARTIFACT_NAME}}

  extract_locales:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        id: build
        uses: ./.github/actions/build-docker

      - name: Cache Dependencies Directory
        uses: ./.github/actions/cache-deps

      - name: Extract Locales
        uses: ./.github/actions/run-docker
        with:
          compose_file: docker-compose.yml
          run: |
            make extract_locales

      - name: Push Locales
        if: github.event_name == 'push'
        shell: bash
        run: |
          make push_locales
