name: Release

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  context:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        run: |
          cat <<EOF
          ${{toJson(github)}}
          EOF


