name: Release Master
on:
  # Runs when there is a push to the default branch
  # This triggers tests and a pushed "latest" image
  # That is deployed to the "dev" environment
  push:
    branches:
      - master
  # TODO REMOVE THIS BEFORE MERGING
  pull_request:

jobs:
  context:
    runs-on: ubuntu-latest

    outputs:
      is_release_master: ${{ steps.context.outputs.is_release_master }}
      version: latest

    steps:
      - uses: actions/checkout@v4
      - id: context
        uses: ./.github/actions/context

  build_prod:
    needs: context
    uses: ./.github/workflows/_build.yml
    with:
      target: production
      version: ${{ needs.context.outputs.version }}

  build_dev:
    needs: context
    uses: ./.github/workflows/_build.yml
    with:
      target: development
      version: ${{ needs.context.outputs.version }}

  test:
    needs: build_dev
    uses: ./.github/workflows/_test.yml
    with:
      artifact_name: ${{ needs.build_dev.outputs.artifact_name }}

  test_main:
    needs: build_dev
    uses: ./.github/workflows/_test_main.yml
    with:
      artifact_name: ${{ needs.build_dev.outputs.artifact_name }}

  publish:
    # TODO UNCOMMENT BEFORE MERGING
    # if: ${{ needs.context.outputs.is_release_master == 'true' }}
    needs: [build_prod, context]
    runs-on: ubuntu-latest

    steps:
      - uses: actions//checkout@v4

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Download Docker image
        id: image
        uses: ./.github/actions/download-docker
        with:
          artifact_name: ${{ needs.build_prod.outputs.artifact_name }}

      - name: Push Docker image
        uses: ./.github/actions/tag-and-push
        with:
          from_tag: ${{ steps.image.outputs.tag }}
          to_registry: docker.io
          to_image: ${{ github.repository }}
          to_version: ${{ steps.image.outputs.version }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

