name: Release Master
on:
  # Runs when there is a push to the default branch
  # This triggers tests and a pushed "latest" image
  # That is deployed to the "dev" environment
  push:
    branches:
      - master
  # TODO REMOVE THIS BEFORE MERGING
  pull_request:

jobs:
  context:
    runs-on: ubuntu-latest

    outputs:
      is_release_master: ${{ steps.context.outputs.is_release_master }}

    steps:
      - uses: actions/checkout@v4
      - id: context
        uses: ./.github/actions/context

  build_prod:
    uses: ./.github/workflows/_build.yml
    with:
      target: production
      version: latest-next

  build_dev:
    uses: ./.github/workflows/_build.yml
    with:
      target: development
      version: latest-next

  test:
    needs: build_dev
    uses: ./.github/workflows/_test.yml
    with:
      artifact_name: ${{ needs.build_dev.outputs.artifact_name }}

  test_main:
    needs: build_dev
    uses: ./.github/workflows/_test_main.yml
    with:
      artifact_name: ${{ needs.build_dev.outputs.artifact_name }}

  publish:
    # TODO UNCOMMENT BEFORE MERGING
    # if: ${{ needs.context.outputs.is_release_master == 'true' }}
    needs: [build_prod, context]
    uses: ./.github/workflows/_publish.yml
    secrets:
      username: ${{ secrets.DOCKER_USER }}
      password: ${{ secrets.DOCKER_PASS }}
    with:
      artifact_name: ${{ needs.build_prod.outputs.artifact_name }}
      registry: docker.io
      image: ${{ github.repository }}
