name: Verify Docker Image

on:
  pull_request:
    branches:
      - master

jobs:
  django_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: build
        uses: ./.github/actions/build-docker
      - name: Django Check
        uses: ./.github/actions/run-docker
        with:
          image: ${{ steps.build.outputs.tags }}
          options:
          run: |
            make update_deps
            echo 'from olympia.lib.settings_base import *' > settings_local.py
            DJANGO_SETTINGS_MODULE='settings_local' python3 ./manage.py check

