name: Verify Docker Image

on:
  pull_request:
    branches:
      - master

jobs:
  docker_config_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
      - name: Install dependencies
        shell: bash
        run: npm ci
      - name: Check make/docker configuration
        shell: bash
        run: |
          docker compose version
          npm exec jest -- ./tests/make --runInBand

  verify_docker_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        id: build
        uses: ./.github/actions/build-docker
        with:
          target: development

      - name: Create failure
        id: failure
        uses: ./.github/actions/run-docker
        with:
          version: ${{ steps.build.outputs.digest }}
          run: |
            exit 1
        continue-on-error: true
      - name: Verify failure
        if: always()
        run: |
          if [ "${{ steps.failure.outcome }}" -ne "failure" ]; then
            echo "Expected failure"
            exit 1
          fi

      - name: Manage py check
        uses: ./.github/actions/run-docker
        with:
          digest: ${{ steps.build.outputs.digest }}
          run: |
            make check
            # Check (special characters in command are not expanded before running on the container)
            echo "this is a question?"
            echo "a * is born"
            echo "wow an array []"
